version: '3'

services:
    frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - './:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        restart: unless-stopped
        environment:
            - NODE_ENV=development
            