version: '3'

services:
    frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile.prod
        volumes:
            - ./nginx:/etc/nginx/conf.d
        restart: unless-stopped
        ports:
            - "80:80"
        environment:
            - NODE_ENV=production