version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
      args: 
        - http_proxy=http://proxy.cs.ui.ac.id:8080
        - https_proxy=http://proxy.cs.ui.ac.id:8080
        - GENERATE_SOURCEMAP=false
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
