version: '3'

services:
    frontend:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - './:/app'
            - '/app/node_modules'
        ports:
            - '3113:3113'
        restart: unless-stopped